default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV.fetch('PGHOST', 'localhost') %>
  username: <%= ENV.fetch('PGUSER', 'root') %>
  password: <%= ENV.fetch('PGPASSWORD', 'root') %>
  port:     <%= ENV.fetch('PGPORT', '5432') %>
  pool:     <%= ENV.fetch('DB_POOL', 5) %>
  timeout: 5000
  reaping_frequency: <%= ENV.fetch('DB_REAPING_FREQUENCY', 10) %>

development:
  <<: *default
  database: employee_review_development
  pool: 20

test:
  <<: *default
  database: employee_review_test
  pool: 20
